### ISSUE TITLE
about barcode fraction

### ISSUE THREAD

**Issue by longzhangnation** [markhilt/ARBitR#1]
hello,
  I'm going to use AnVIL to saffold my genome with 10X genomics sequencing,But I don't know what's the meaning of '-f BARCODE_FRACTION'.So could you please tell me the meaning and use of this parameter?
  Thanks a lot.

**Comment by markhilt** [comment]
Hi,
Sorry about the delay. --barcode_fraction is a hard cutoff for the minimum fraction of shared barcodes. An edge will not be formed in the link graph if the fraction between two contig ends is below this value, even if the fraction is significantly higher than the rest. Usually this value does not need to be changed from the default.
