### ISSUE TITLE
Scaffolding supernova 10x

### ISSUE THREAD

**Issue by shabirmoosa** [markhilt/ARBitR#5]
hi,

Could you provide more info on how I can scaffold the fasta files generated using supernova assembly ?

**Comment by markhilt** [comment]
Hi!
The principle is the same as for any assembly: Map the linked reads with the mapper of your choice (though make sure the barcode is given in the BX tag) and provide the fasta and bam files to ARBitR.

Supernova can create different fasta files depending on your needs. If you're using ARBitR I'm guessing you want the "pseudohap" format from supernova.
